environment:
  matrix:
  - TOOLCHAIN: stable

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --profile minimal --default-toolchain %TOOLCHAIN%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

before_build:
  - cargo update

build_script:
  - cargo build --verbose

test_script:
  - cargo test --verbose

cache:
  - '%USERPROFILE%\.cargo'
  - target
